#!/bin/bash

set -e

db_name=$1

if [[ -z $db_name  ]]; then
  echo 'No database name given: script/import-psql $DB_NAME';
  exit
fi

# Drop and recreate the database
dropdb --if-exists -i $db_name
createdb $db_name

# Create the PostGIS extension and load the data schema
psql -c 'create extension postgis' $db_name
psql -f sql/schema.sql $db_name

# Load the Lost In Place tract data
cat data/csv/lost_in_place.csv | \
  psql -c "copy tract_data from stdin with csv header delimiter ',' NULL E'' quote '\"'" $db_name

# Create a couple of useful indexes
psql -c 'create unique index tract_id_idx on tract_data (tractid)' $db_name
psql -c 'create index cbsa_title_idx on tract_data (lower(cbsa_title))' $db_name

# Download and extract data
make data/gz/nhgis_tract_2010.zip

shp2pgsql -W "latin1" -I -D -d -i -s 4326 data/shp/US_tract_2010.shp tracts | psql -d $db_name
